### ISSUE TITLE
Unable to connect to existing cloud cluster

### ISSUE THREAD

**Issue by tischulz1** [BiBiServ/bibigrid#200]
Hi,
I am currently experiencing problems when trying to connect to my existing cloud cluster at Giessen. I have set up that cluster already some time ago using Bibigrid version 2.0.7, but neither with that old version, nor with version 2.0.9 it is possible now.
The error message looks like the following:

`>java -jar bibigrid-openstack-2.0.9.jar -ch -o ~/[...]/bibigrid1.yml
Ok : Use openstack provider.
Ok : Using alternative config file: '/[...]/bibigrid1.yml'.
Ok : Openstack connection established.
Exception in thread "main" ClientResponseException{message=Status: 403, Reason: Forbidden, status=403, status-code=FORBIDDEN}
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
	at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
	at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:101)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:47)
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.getEntity(HttpResponseImpl.java:64)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:225)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:207)
	at org.openstack4j.openstack.compute.internal.FlavorServiceImpl.list(FlavorServiceImpl.java:63)
	at org.openstack4j.openstack.compute.internal.FlavorServiceImpl.list(FlavorServiceImpl.java:48)
	at org.openstack4j.openstack.compute.internal.FlavorServiceImpl.list(FlavorServiceImpl.java:32)
	at de.unibi.cebitec.bibigrid.openstack.ProviderModuleOpenstack.getInstanceTypeMap(ProviderModuleOpenstack.java:77)
	at de.unibi.cebitec.bibigrid.core.model.ProviderModule.getInstanceTypes(ProviderModule.java:91)
	at de.unibi.cebitec.bibigrid.core.model.ProviderModule.getInstanceType(ProviderModule.java:75)
	at de.unibi.cebitec.bibigrid.core.Validator.validateProviderTypes(Validator.java:237)
	at de.unibi.cebitec.bibigrid.StartUp.runIntent(StartUp.java:227)
	at de.unibi.cebitec.bibigrid.StartUp.main(StartUp.java:164)`

Using the openstack client directly works perfectly fine for me though.

What is the problem here and how can I solve it?

**Comment by jkrue** [comment]
Dear Tizian,

the de.NBI cloud site Giessen upgraded their OpenStack version.
Seems that not all API endpoints works as expected. The cloud team in Giessen informed.

Best Jan

> On 18. Oct 2019, at 11:10, tischulz1 <notifications@github.com> wrote:
> 
> Hi,
> I am currently experiencing problems when trying to connect to my existing cloud cluster at Giessen. I have set up that cluster already some time ago using Bibigrid version 2.0.7, but neither with that old version, nor with version 2.0.9 it is possible now.
> The error message looks like the following:
> 
> >java -jar bibigrid-openstack-2.0.9.jar -ch -o ~/[...]/bibigrid1.yml Ok : Use openstack provider. Ok : Using alternative config file: '/[...]/bibigrid1.yml'. Ok : Openstack connection established. Exception in thread "main" ClientResponseException{message=Status: 403, Reason: Forbidden, status=403, status-code=FORBIDDEN} at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38) at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23) at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:101) at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:47) at org.openstack4j.connectors.resteasy.HttpResponseImpl.getEntity(HttpResponseImpl.java:64) at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:225) at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:207) at org.openstack4j.openstack.compute.internal.FlavorServiceImpl.list(FlavorServiceImpl.java:63) at org.openstack4j.openstack.compute.internal.FlavorServiceImpl.list(FlavorServiceImpl.java:48) at org.openstack4j.openstack.compute.internal.FlavorServiceImpl.list(FlavorServiceImpl.java:32) at de.unibi.cebitec.bibigrid.openstack.ProviderModuleOpenstack.getInstanceTypeMap(ProviderModuleOpenstack.java:77) at de.unibi.cebitec.bibigrid.core.model.ProviderModule.getInstanceTypes(ProviderModule.java:91) at de.unibi.cebitec.bibigrid.core.model.ProviderModule.getInstanceType(ProviderModule.java:75) at de.unibi.cebitec.bibigrid.core.Validator.validateProviderTypes(Validator.java:237) at de.unibi.cebitec.bibigrid.StartUp.runIntent(StartUp.java:227) at de.unibi.cebitec.bibigrid.StartUp.main(StartUp.java:164)
> 
> Using the openstack client directly works perfectly fine for me though.
> 
> What is the problem here and how can I solve it?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

---
Jan Krüger

Bielefeld University Bioinformatics Server (BiBiServ)
Center for Biotechnology (CeBiTec)

Bielefeld University
Faculty of Technology
33594 Bielefeld,Germany

room    : M3-120
phone  : +49 (521) 106 2494
