### ISSUE TITLE
Java-9 is unsupported.

### ISSUE THREAD

**Issue by marscher** [BiBiServ/bibigrid#29]

**Comment by maitai** [comment]
@marscher: Running ab29980 `java -jar BiBiGrid-1.0.jar -l` on **Java 9b134** with OpenStack as the target cloud outputs some warnings. Is that what you are referring to?

        org.glassfish.jersey.internal.Errors logErrors
        WARNING: The following warnings have been detected: WARNING: HK2 service reification failed for [org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
        MultiException stack 1 of 2
        java.lang.NoClassDefFoundError: javax/activation/DataSource
                at java.lang.Class.getDeclaredConstructors0(java.base@9-ea/Native Method)
                at java.lang.Class.privateGetDeclaredConstructors(java.base@9-ea/Class.java:2918)
                at java.lang.Class.getDeclaredConstructors(java.base@9-ea/Class.java:2208)
                at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1311)
         
                [...]
         
                at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
                at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:84)
                at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65)
                at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
                at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
                at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
                at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:122)
                at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:52)
                at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:117)
                at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:79)
                at de.unibi.cebitec.bibigrid.meta.openstack.OpenStackIntent.buildOSClient(OpenStackIntent.java:47)
                at de.unibi.cebitec.bibigrid.meta.openstack.OpenStackIntent.<init>(OpenStackIntent.java:25)
                at de.unibi.cebitec.bibigrid.meta.openstack.ListIntentOpenstack.<init>(ListIntentOpenstack.java:32)
                at de.unibi.cebitec.bibigrid.ctrl.ListIntent.execute(ListIntent.java:53)
                at de.unibi.cebitec.bibigrid.StartUp.main(StartUp.java:161)
        Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
                at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-ea/BuiltinClassLoader.java:366)
                at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-ea/ClassLoaders.java:185)
                at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:419)
                ... 77 more
        MultiException stack 2 of 2
        java.lang.IllegalArgumentException: Errors were discovered while reifying SystemDescriptor(
                implementation=org.glassfish.jersey.message.internal.DataSourceProvider
                contracts={javax.ws.rs.ext.MessageBodyWriter,javax.ws.rs.ext.MessageBodyReader}
                scope=javax.inject.Singleton
                qualifiers={}
                descriptorType=CLASS
                descriptorVisibility=NORMAL
                metadata=
                rank=0
                loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@4983159f
                proxiable=null
                proxyForSameScope=null
                analysisName=null
                id=12
                locatorId=1
                identityHashCode=1155769010
                reified=false)
                at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:689)
         
                [...]
         
                at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
                at org.openstack4j.connectors.jersey2.HttpCommand.execute(HttpCommand.java:84)
                at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:65)
                at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:56)
                at org.openstack4j.connectors.jersey2.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:33)
                at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
                at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV2(OSAuthenticator.java:122)
                at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:52)
                at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:117)
                at org.openstack4j.openstack.client.OSClientBuilder$ClientV2.authenticate(OSClientBuilder.java:79)
                at de.unibi.cebitec.bibigrid.meta.openstack.OpenStackIntent.buildOSClient(OpenStackIntent.java:47)
                at de.unibi.cebitec.bibigrid.meta.openstack.OpenStackIntent.<init>(OpenStackIntent.java:25)
                at de.unibi.cebitec.bibigrid.meta.openstack.ListIntentOpenstack.<init>(ListIntentOpenstack.java:32)
                at de.unibi.cebitec.bibigrid.ctrl.ListIntent.execute(ListIntent.java:53)
                at de.unibi.cebitec.bibigrid.StartUp.main(StartUp.java:161)

**Comment by marscher** [comment]
It was not a warning, but a nullpointer exception at the top of the stack. We used the bibigrid version of the workshop tutorial (I will report back with the exact version when I'm back on my laptop).

**Comment by jkrue** [comment]
Since Java 9 is not finished - even not in RC state - it doesn't make sense to fix anything to be compatible with the current Java 9 build (see timeline on http://openjdk.java.net/projects/jdk9/). The problem could be within the project **or** could rely on the used Java 9 build, who knows ...
