### ISSUE TITLE
Can't be started from cmdline when build using "mvn package"

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#60]
When build BiBiGrid using `mvn package -Dmaven.test.skip=true` the packaged Java archive fails, e.g.:
```
$ java -jar BiBiGrid-Main-1.1.jar -o /Users/jkrueger/.bibigrid.properties -l
Ok : Alternative config file /Users/jkrueger/.bibigrid.properties will be used.
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:964)
        at org.openstack4j.connectors.resteasy.executors.ApacheHttpClientEngine.create(ApacheHttpClientEngine.java:75)
        at org.openstack4j.connectors.resteasy.HttpCommand.initialize(HttpCommand.java:46)
        at org.openstack4j.connectors.resteasy.HttpCommand.create(HttpCommand.java:40)
        at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:52)
        at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:31)
        at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:51)
        at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV3(OSAuthenticator.java:187)
        at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:74)
        at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:172)
        at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:129)
        at de.unibi.cebitec.bibigrid.openstack.OpenStackUtils.buildOSClientV3(OpenStackUtils.java:36)
        at de.unibi.cebitec.bibigrid.openstack.OpenStackUtils.buildOSClient(OpenStackUtils.java:16)
        at de.unibi.cebitec.bibigrid.openstack.ListIntentOpenstack.<init>(ListIntentOpenstack.java:30)
        at de.unibi.cebitec.bibigrid.openstack.ProviderModuleOpenstack.getListIntent(ProviderModuleOpenstack.java:35)
        at de.unibi.cebitec.bibigrid.StartUp.runIntent(StartUp.java:140)
        at de.unibi.cebitec.bibigrid.StartUp.main(StartUp.java:94)
``` 
Running the same setup directly from an IDE works ...

**Comment by pbelmann** [comment]
Maybe a different maven version?

**Comment by jkrue** [comment]
Unfortunatly not, it's the same maven version in both cases (but not the same installation).

**Comment by jkrue** [comment]
The problem is that three of the four cloud SDKs  (AWS,Google,Openstack4J) uses different versions of the same Apache httpclient/core library.

Lib\SDK | Openstack4J | AWS | Google
-------- | ------------- | ----- | -------
**httpclient** | 4.5.3| 4.5.2 | 4.0.1
**httpcore** | 4.4.6 | 4.4.4 | 4.0.1

**Comment by jkrue** [comment]
Welcome in the Java dependency hell . This is nothing we could solve without Java 9 (Project Jigsaw). In my opinion, the best solution for now to solve this dilemma is to provide different pom's for each cloud provider SDK.

**Comment by jkrue** [comment]
Life could be so easy ;-) Maven profiles is the (not so bad)  solution for our dependency problem.
