### ISSUE TITLE
Creating a cluster from shaded jar fails ...

### ISSUE THREAD

**Issue by jkrue** [BiBiServ/bibigrid#66]
... with following exception:
```
Ok : Upload Ansible playbook to master instance.
Ok : Connecting sftp channel...
ERROR: SFTP: {} [CreateCluster:300]
com.jcraft.jsch.SftpException: No such file
        at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2846) ~[bibigrid-openstack-2.0.jar:na]
        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:753) ~[bibigrid-openstack-2.0.jar:na]
        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:700) ~[bibigrid-openstack-2.0.jar:na]
        at com.jcraft.jsch.ChannelSftp.put(ChannelSftp.java:694) ~[bibigrid-openstack-2.0.jar:na]
        at de.unibi.cebitec.bibigrid.core.intents.CreateCluster.uploadAnsibleToMaster(CreateCluster.java:289) [bibigrid-openstack-2.0.jar:na]
        at de.unibi.cebitec.bibigrid.core.intents.CreateCluster.configureMaster(CreateCluster.java:244) [bibigrid-openstack-2.0.jar:na]
        at de.unibi.cebitec.bibigrid.core.intents.CreateCluster.launchClusterInstances(CreateCluster.java:124) [bibigrid-openstack-2.0.jar:na]
        at de.unibi.cebitec.bibigrid.StartUp.runIntent(StartUp.java:158) [bibigrid-openstack-2.0.jar:na]
        at de.unibi.cebitec.bibigrid.StartUp.main(StartUp.java:93) [bibigrid-openstack-2.0.jar:na]
ERROR: Master instance configuration failed! [CreateCluster:255]

```

The same action initiated by the IDE (Intellj) works like a charm ...

**Comment by AstrorEnales** [comment]
He possibly doesn't find the ansible resources in the jar file, or they are not included. Will take a look at it...

**Comment by jkrue** [comment]
The ansible resources are included ...
```
$ jar -tf bibigrid-openstack-2.0.jar | grep "playbook"
playbook/
playbook/ansible_hosts
playbook/vars/
playbook/vars/common.yml
playbook/site.yml
playbook/roles/
...
```

**Comment by AstrorEnales** [comment]
As i thought, since the resources were bundled into a jar file the code couldn't find them. I added a check if it's bundled or not and load them accordingly.
