### ISSUE TITLE
nfs share error

### ISSUE THREAD

**Issue by wpaetzold** [BiBiServ/bibigrid#81]
This type of code:
```
nfsShares:
  - /vol/dicontrol 
```
 produces the following error:
```
ERROR: Aborting operation. No instances started/terminated. [StartUp:160]
de.unibi.cebitec.bibigrid.core.model.exceptions.ConfigurationException: Failed to parse configuration file.
        at de.unibi.cebitec.bibigrid.core.util.DefaultPropertiesFile.loadConfiguration(DefaultPropertiesFile.java:83)
        at de.unibi.cebitec.bibigrid.core.CommandLineValidator.<init>(CommandLineValidator.java:40)
        at de.unibi.cebitec.bibigrid.openstack.CommandLineValidatorOpenstack.<init>(CommandLineValidatorOpenstack.java:29)
        at de.unibi.cebitec.bibigrid.openstack.ProviderModuleOpenstack.getCommandLineValidator(ProviderModuleOpenstack.java:31)
        at de.unibi.cebitec.bibigrid.StartUp.runIntent(StartUp.java:158)
        at de.unibi.cebitec.bibigrid.StartUp.main(StartUp.java:107)
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: Cannot create property=nfsShares for JavaBean=de.unibi.cebitec.bibigrid.openstack.ConfigurationOpenstack@6f195bc3
 in 'reader', line 3, column 1:
    mode: openstack
    ^
 in 'reader', line 44, column 3:
      - /vol/dicontrol    
      ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:270)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:518)
        at de.unibi.cebitec.bibigrid.core.util.DefaultPropertiesFile.loadConfiguration(DefaultPropertiesFile.java:79)
        ... 5 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.yaml.snakeyaml.introspector.MethodProperty.set(MethodProperty.java:77)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:263)
        ... 14 common frames omitted
Caused by: java.lang.UnsupportedOperationException: null
        at java.util.AbstractList.add(AbstractList.java:148)
        at java.util.AbstractList.add(AbstractList.java:108)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
        at de.unibi.cebitec.bibigrid.core.model.Configuration.setNfsShares(Configuration.java:244)
        ... 20 common frames omitted
```

**Comment by wpaetzold** [comment]
Hi,
thx. I tried to start my instances again, but it is still not working for me. Here my config.yml:

```
# Comment

mode: openstack

#Access
user: ubuntu
sshUser: ubuntu
keypair: XXX_key
sshPublicKeyFile: key.pub
sshPrivateKeyFile: openstack.key


region: Bielefeld
availabilityZone: default

subnet: control-subnet
ports:
  - type: TCP
    number: 80

useMasterAsCompute: no

masterInstance:
  type: de.NBI.large
  image: febceb9a-fb0f-4f1c-ad06-8caf6340de64

slaveInstances:
  - type: de.NBI.large
    count: 3
    image: febceb9a-fb0f-4f1c-ad06-8caf6340de64


oge: yes
spark: yes
nfs: yes
cloud9: yes

nfsShares:
  - /mnt 

masterMounts:
  - source: adff8def-d47i-43e98-9b1b-gdt64rml8f7
    target: /mnt
```
I am trying to mount my volume to the master `/mnt` folder. Then this folder should be shared with all the slave instances via nfs. After your fix the error messages are gone, but it is still not functioning. There is no nfs. The volume is attached to the master instance, but not mounted to `/mnt`
